### ISSUE TITLE
Allow header manipulation for every script.

### ISSUE THREAD

**Issue by pavlov99** [pavlov99/tabtools#7]
Header could be set up from script parameters via `--header` argument.
Header could be omitted in the output vis `--no-header` argument. 

See also: convert csv file to tsv with proper header format

``` bash
cat <(printf "# ") <(cat file.csv | tr "," "\t")
```

**Comment by aekazitt** [comment]
Can be done by adding add_mutually_exclusive_group() in awk()'s argparse variable.

**Comment by pavlov99** [comment]
@aekazitt This code should do the job: https://github.com/pavlov99/tabtools/blob/master/tabtools/scripts.py#L20-L34

This issue became resolved.
